### ISSUE TITLE
Is the cm-eval package published yet?

### ISSUE THREAD

**Issue by ojack** [mindofmatthew/text.management#10]
Was trying to test it out but couldn't find it :)

**Comment by mindofmatthew** [comment]
Okay, it's up! I'm still not totally certain about my release workflow (I'm using NPM workspaces for the first time), but I think everything should be good, so I'll release it as 0.1 for now and then bump it to a real version when we can verify that it works somewhere else.

Let me know if you have any issues with installing, or have feature/documentation requests! The interface is a single extension that wraps up several tiny extensions (one for styling, one for key commands, etc), and all of the individual pieces are exported [here](https://github.com/mindofmatthew/text.management/blob/main/packages/codemirror/evaluate/src/index.ts), so any custom configuration should be possible. That said, I'm also open to changes once I've got a better idea of other folks' use-cases.

https://www.npmjs.com/package/@management/cm-evaluate
