### ISSUE TITLE
don't keep the background of the error console red for as long

### ISSUE THREAD

**Issue by cleary** [mindofmatthew/text.management#36]
Hey Matt, this is is really nice, thanks so much for making it!

One thing I'm finding is that after I evaluate something and an error is thrown, it sometimes confuses me for subsequent evaluationss because it is still there and red even though my code is fine after fixing the issue. 

I was thinking that maybe it'd be good if it could just flash red and fade out, so you know it's an error *now*
Another option could be to change the background colour on a successful eval from red to something non-descript

Many possibilities I'm sure, don't have a particular preference but just looking for it to be easier to map errors to actions in time.

Thanks :)

**Comment by mindofmatthew** [comment]
The background is per-message, and I like that aspect of it. That said, I think that a good default mode might be to only display the result of the most recent evaluation and then to clear the console each time there's a successful evaluation. That's how Hydra handles it, and you're right that that's really all you need while performing.

I like having the console history when I'm debugging Tidal things (for example, comparing the printed results of multiple patterns), but that's a specialized usage, and one that requires opting in.

**Comment by cleary** [comment]
I discovered through my overriding vim habits that esc clears the error log too - that's actually a pretty good workaround for me atm :)
