### ISSUE TITLE
Utility Request: Timer

### ISSUE THREAD

**Issue by reckoner165** [mindofmatthew/text.management#74]
This is less of a text editor feature and more a livecode-performance utility: It would be good to have a timer that can be set to show countdown/ logs when the (wall clock) time has run out. 
This will be useful in a performance context for keeping track of time from within the editor window.

One UI idea for this is showing a persistent circle timer (on the top right, perhaps?) with green/yellow/red depending on some configurable thresholds. 
Examples: 
https://www.npmjs.com/package/react-countdown-circle-timer
https://flxng.codeeve.com/#/circle-timer

**Comment by mindofmatthew** [comment]
The easiest thing to incorporate would probably be a text-based timer in the bottom bar, something like this:

![image](https://github.com/mindofmatthew/text.management/assets/911429/3aab6fcb-8d9a-478e-acff-37d1c8421249)

I can imagine that it would have a solid yellow/blinking red background depending on the threshold (perhaps also popping messages into the console). Do you think that would be sufficiently eye-catching, or would you prefer something larger like the references you shared?

If you wanted more of a circle "widget" timer, maybe it could go in some sort of separate panel to the right of the code editing pane?

**Comment by reckoner165** [comment]
Yeah, I think this is sufficiently eye-catching, and easily available without needing to leave the editor window. 
I'm not beholden to the circle, but it would be useful to have some representation of the actual time as well as "% time left" in some form. Would it make sense to simply print the % as well? I suppose the color coding indicates this to an extent too.

Happy to try out a feature-branch if you have a working version of this somewhere!
